version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:pr-2419
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8020:8020 # Qbittorrent
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 9696:9696 # Prowlarr
      - 8686:8686 # Lidarr
      - 8191:8191 # Flaresolverr 
    volumes:
      - /home/rcrumana/Dev/docker/gluetun:/gluetun
    environment:
      # Trust Me Bro
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # Wireguard: config
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PORT_FORWARDING_PROVIDER}
      - TZ=${TZ}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      - HEALTH_TARGET_ADDRESS=${HEALTH_TARGET_ADDRESS}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    privileged: true
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8020
    volumes:
      - /home/rcrumana/Dev/docker/qbittorrent:/config
      - /media/Torrent/Downloads:/downloads
      - /media/Torrent/Movies:/movies
      - /media/Torrent/Shows:/shows
      - /media:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/rcrumana/Dev/docker/sonarr:/config
      - /media/Torrent/Shows:/tv
      - /media/Torrent/Downloads:/downloads
      - /media:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/rcrumana/Dev/docker/radarr:/config
      - /media/Torrent/Movies:/movies
      - /media/Torrent/Downloads:/downloads
      - /media:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/rcrumana/Dev/docker/lidarr:/config
      - /media/Torrent/Music:/music
      - /media/Torrent/Downloads:/downloads
      - /media:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/rcrumana/Dev/docker/prowlarr:/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
    
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Los_Angeles
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
