version: "3"
services:
  gluetun_lts:
    image: qmcgaw/gluetun:pr-2419
    container_name: gluetun_lts
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6882:6882
      - 6882:6882/udp
      - 8021:8021 # Qbittorrent_lts
    volumes:
      - /home/rcrumana/Dev/docker/gluetun_lts:/gluetun
    environment:
      # Trust Me Bro
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # Wireguard: config
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PORT_FORWARDING_PROVIDER}
      - TZ=${TZ}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      - HEALTH_TARGET_ADDRESS=${HEALTH_TARGET_ADDRESS}
      
  qbittorrent_lts:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent_lts
    privileged: true
    network_mode: "service:gluetun_lts"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8021
    volumes:
      - /home/rcrumana/Dev/docker/qbittorrent_lts:/config
      - /media/Torrent/Downloads:/downloads
      - /media/Torrent/Movies:/movies
      - /media/Torrent/Shows:/shows
      - /media:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun_lts:
        condition: service_healthy
    restart: always
