version: "3"
services:
  gluetun_lts2:
    image: qmcgaw/gluetun:pr-2419
    container_name: gluetun_lts2
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6883:6883
      - 6883:6883/udp
      - 8022:8022 # Qbittorrent_lts2
    volumes:
      - /home/rcrumana/Dev/docker/gluetun_lts2:/gluetun
    environment:
      # Trust Me Bro
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # Wireguard: config
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PORT_FORWARDING_PROVIDER}
      - TZ=${TZ}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      - HEALTH_TARGET_ADDRESS=${HEALTH_TARGET_ADDRESS}
      
  qbittorrent_lts2:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent_lts2
    privileged: true
    network_mode: "service:gluetun_lts2"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8022
    volumes:
      - /home/rcrumana/Dev/docker/qbittorrent_lts2:/config
      - /media/Torrent/Downloads:/downloads
      - /media/Torrent/Movies:/movies
      - /media/Torrent/Shows:/shows
      - /media:/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      gluetun_lts2:
        condition: service_healthy
    restart: always
