version: '3.8'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    network_mode: host
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
