version: '3.8'

services:
  portfolio:
    build:
      context: .
    image: portfolio
    ports:
      - "8085:8085"
    environment:
      RUST_LOG: info  # Modify as needed
    restart: unless-stopped
