version: "2.1"
services:
  unifi-db:
    image: mongo:6.0.11
    container_name: unifi-db
    volumes:
      - /home/rcrumana/Dev/docker/unifi/db/data:/data/db
      - /home/rcrumana/Dev/docker/unifi/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MEM_LIMIT=${MEM_LIMIT}
      - MEM_STARTUP=${MEM_STARTUP}
    volumes:
      - /home/rcrumana/Dev/docker/unifi/config:/config
    ports:
      - 8443:8443 # HTTPS portal
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8554:8843 #optional  # HTTPS guest portal
      - 8881:8880 #optional  # HTTP guest portal
      - 6789:6789 #optional  # Mobile speed test port
      - 5514:5514/udp #optional  # Remote syslog port
    restart: unless-stopped
    depends_on:
      - unifi-db
