services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    security_opt:
      - no-new-privileges:true
    ports:
     - 9445:80
    restart: unless-stopped
    environment:
      - DOMAIN=https://vault.rcrumana.xyz
    volumes:
      - ./data:/data
