version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    command:
      - --cleanup=true
      - --remove-volumes=true
      - --label-enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
